### PR TITLE
docs: add direct link to example

### PR DESCRIPTION
**Pull request by grant**
Adds a direct link to the preview. It is very exhausting clicking through every GitHub.com link to find another link to the actual embed example.

Removes the step to "See it live".

Screen Shot 2023-02-22 at 18 11 16

---

Feel free to suggest a different layout.

### CODE REVIEW

**Comment by grant** [comment]
Note: Looks like this repo does not require reviews.

**Comment by tophtucker** [comment]
Yeah makes sense. I'd do a different icon than 🔗 , since the link to the readme is also a link. I think I'd give the table three columns, "Readme", "Live demo", and "Description". And every row in "Live demo" would just say "Live demo", linked.

**Comment by tophtucker** [comment]
Or the first column could be like: 

[react-dataflow](https://github.com/observablehq/examples/tree/main/react-dataflow/) ([demo](https://observablehq.github.io/examples/react-dataflow/))

Anything but an emoji lol. Too hard to find a good self-explanatory emoji for "demo". Words work! 😅

**Comment by grant** [comment]
Updated, thanks for the review.

Sounds fine. As mentioned, feel free to suggest working. I believe the prefix of (demo) rather than suffix makes the documentation more scannable.

**Review by tophtucker — APPROVED** [review]
🙏 as ever, like everyone, i admire and appreciate your proactive spirit

**Comment by grant** [comment]
> 🙏 as ever, like everyone, i admire and appreciate your proactive spirit

This is just the start!

**Pull request merged**
